### PR TITLE
Adding the learning path svg

### PR DESCRIPTION
**Pull request by maboelsoudd2l**
Pretty self-explanatory.

Are there instructions to update the LMS to use the new icon once it has been published?

### CODE REVIEW

**Review by m6jones — COMMENTED** [review]
This looks good from the Business side of things.
I approve when we get approval from the tech side.

**Comment by dlockhart** [comment]
So a few issues here -- it needs to be exactly 60 x 60, and should follow [all the recommendations for our normal core icons](https://github.com/BrightspaceUI/core/tree/master/components/icons#svg-format) around having a width, height, viewBox, no `<style>` blocks or CSS classes. Basically put it through SVGOmg with some of the optimization settings tweaked. But you may need to get a new SVG from the designer that's 60x60... otherwise you'll need to manually scale it.

**Comment by dlockhart** [comment]
Once the icon's in good shape, I can manually get this on the CDN. Then in the monolith there are a couple places to add it to -- [Christine did one last week](https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/10531/overview) so you can just copy that.

**Review by dlockhart — APPROVED** [review]
Looks good! I'll merge and get this on the CDN and I'll send you a link to it.

**Pull request merged**
